version: 2.1

jobs:
  build:
    docker:
      - image: node:14.17.0
    steps:
      - checkout
      - run: npm install
      - run: node app.js
  deploy:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t ${DOCKERHUB_USERNAME}/node-app:${CIRCLE_SHA1} .
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push ${DOCKERHUB_USERNAME}/node-app:${CIRCLE_SHA1}
  test:
    docker:
      - image: node:14.17.0
    steps:
      - checkout
      - run: npm install
      - run: node app.js

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - test:
          requires:
            - deploy
