version: 2.1

jobs:
  deploy:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t ${DOCKERHUB_USERNAME}/node-app:${CIRCLE_SHA1} .
          docker login -u ${DOCKERHUB_USERNAME} --password-stdin
          docker push ${DOCKERHUB_USERNAME}/node-app:${CIRCLE_SHA1}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
          
    
